name: AI Chat - Dynamic (Python Backend)

on:
  workflow_dispatch:
    inputs:
      ai_type:
        description: 'The AI to use (gemini, openai, claude)'
        required: true
        default: 'gemini'
      user_message:
        description: 'The user message'
        required: true

jobs:
  process-chat:
    runs-on: ubuntu-latest
    permissions:  # Add permissions here!
      actions: write        # Needed to trigger workflow dispatches
      contents: write       # Needed to read and write to the repository (conversation_history.json, index.html)
      issues: read         # Needed for the initial strategy, can remove if not going for dynamic
      #pull-requests: write  # If you were using PRs for comments, you'd need this.
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Get Conversation History
        id: get-history
        run: |
          if [ -f conversation_history.json ]; then
            echo "::set-output name=history::$(cat conversation_history.json)"
          else:
            echo "::set-output name=history::[]"

      - name: Process Chat Request
        id: process
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
        run: |
          python -u ./process_chat.py

      - name: Replace Placeholder in index.html
        run: |
          sed -i 's/YOUR_ACTIONS_PAT_PLACEHOLDER/${{ secrets.ACTIONS_PAT }}/g' index.html

      - name: Commit and Push Changes
        uses: EndBug/add-and-commit@v9
        with:
          add: 'conversation_history.json index.html'
          message: 'Update conversation history and injected PAT'
          push: true
